# Generated by Django 5.1.5 on 2025-02-10 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_options_review_owner'),
        ('users', '0004_rename_skilll_skill_profile_location'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('owner', 'project')},
        ),
    ]
